[package]
name = "bootloader-x86_64-common"
version.workspace = true
edition = "2021"
description = "Common code for the x86_64 bootloader implementations"
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader_api = { workspace = true }
bootloader-boot-config = { workspace = true }
conquer-once = { version = "0.3.2", default-features = false }
spinning_top = "0.2.4"
usize_conversions = "0.2.0"
x86_64 = { version = "0.15.2" }
xmas-elf = "0.8.0"
raw-cpuid = "10.2.0"
rand = { version = "0.8.4", default-features = false }
rand_hc = "0.3.1"
uart_16550 = "0.3.2"
log = "0.4.17"

[dependencies.noto-sans-mono-bitmap]
version = "0.2.0"
default-features = false
features = [
    "regular",
    "size_16",
    "unicode-basic-latin",
    # required for the fallback char 'ï¿½'
    "unicode-specials",
]
