name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: crates_io_release

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v1

      - run: cargo publish -p bootloader_api
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - run: cargo publish -p bootloader-boot-config
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - run: cargo publish -p bootloader-x86_64-bios-common
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - run: cargo publish -p bootloader-x86_64-common
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - run: cargo publish -p bootloader-x86_64-bios-boot-sector --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - run: cargo publish -p bootloader-x86_64-bios-stage-2 --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - run: cargo publish -p bootloader-x86_64-bios-stage-3 --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - run: cargo publish -p bootloader-x86_64-bios-stage-4 --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - run: cargo publish -p bootloader-x86_64-uefi --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - run: cargo publish -p bootloader
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
